. "$PSScriptRoot\common.ps1"

$repoRoot = Resolve-Path "$PSScriptRoot\..\.."
Push-Location "$repoRoot\backend"
try {
    .\mvnw.cmd test
    if ($LASTEXITCODE -ne 0) { throw "Backend unit tests failed." }
    .\mvnw.cmd verify -Pintegration
    if ($LASTEXITCODE -ne 0) { throw "Backend integration tests failed." }
}
finally {
    Pop-Location
}

Push-Location "$repoRoot\load-tests"
try {
    & ".\scripts\run-smoke.ps1"
    & ".\scripts\run-correctness.ps1"
    & ".\scripts\run-baseline.ps1"

    New-Item -ItemType Directory -Force -Path "$repoRoot\docs\performance" | Out-Null
    $commit = git -C $repoRoot rev-parse HEAD
    $date = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
    @"
# TicketForge PostgreSQL Baseline

Date: $date
Commit SHA: $commit

This report was generated by load-tests/scripts/run-all.ps1.
Review the JSON summaries under load-tests/results/ for RPS, P50, P90, P95, P99, max latency, dropped iterations, and correctness counters.

These are provisional guardrails, not production SLOs.
"@ | Set-Content -Path "$repoRoot\docs\performance\baseline.md" -Encoding utf8
}
finally {
    Pop-Location
}
